#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Getanolina.Resource", IsApplication=true)]

namespace Getanolina
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Getanolina.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int anoSpinner = 2131034119;
			
			// aapt resource value: 0x7f050016
			public const int buttonCalcular = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int editTextAlcool = 2131034130;
			
			// aapt resource value: 0x7f05001e
			public const int editTextConAlco = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int editTextConGNV = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int editTextConGas = 2131034141;
			
			// aapt resource value: 0x7f050024
			public const int editTextCusAlc = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int editTextCusGNV = 2131034149;
			
			// aapt resource value: 0x7f050023
			public const int editTextCusGas = 2131034147;
			
			// aapt resource value: 0x7f050013
			public const int editTextGNV = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int editTextGasolina = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int editTextKm = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int editTextKmMensal = 2131034123;
			
			// aapt resource value: 0x7f050021
			public const int editTextMenAlc = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int editTextMenGNV = 2131034146;
			
			// aapt resource value: 0x7f050020
			public const int editTextMenGas = 2131034144;
			
			// aapt resource value: 0x7f05001b
			public const int editTextRendAlco = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int editTextRendGNV = 2131034140;
			
			// aapt resource value: 0x7f05001a
			public const int editTextRendGas = 2131034138;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050014
			public const int linearLayout2 = 2131034132;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout3 = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int linearLayout4 = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int linearLayout5 = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int linearLayout6 = 2131034137;
			
			// aapt resource value: 0x7f050003
			public const int marcaSpinner = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int modeloSpinner = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int textView10 = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int textView2 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textView3 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int textView4 = 2131034120;
			
			// aapt resource value: 0x7f050015
			public const int textView5 = 2131034133;
			
			// aapt resource value: 0x7f05000d
			public const int textView6 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int textView7 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int textView8 = 2131034127;
			
			// aapt resource value: 0x7f050018
			public const int textView9 = 2131034136;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int SelecionaAno = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int SelecionaMarca = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SelecionaModelo = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
